export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_BY_CATEGORY = 'GET_POSTS_BY_CATEGORY';
export const GET_POSTS_BY_POPULAR = 'GET_POSTS_BY_POPULAR';
export const GET_POSTS_BY_LATEST = 'GET_POSTS_BY_LATEST';
export const SET_LOADED = 'SET_LOADED';
