export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const GET_POSTS_BY_LATEST = 'GET_POSTS_BY_LATEST';
export const GET_POSTS_BY_POPULAR = 'GET_POSTS_BY_POPULAR';
export const SET_LOADED = 'SET_LOADED';
export const SET_LOADED_POSTS_BY_LATEST = 'SET_LOADED_POSTS_BY_LATEST';
export const SET_LOADED_POSTS_BY_POPULAR = 'SET_LOADED_POSTS_BY_POPULAR';
export const SET_LOADED_CREATE_POST = 'SET_LOADED_CREATE_POST';
export const SET_LOADED_GET_POST = 'SET_LOADED_GET_POST';
export const SET_LOADED_UPDATE_POST = 'SET_LOADED_UPDATE_POST';

export const ADD_LIKE = 'ADD_LIKE';
export const SET_LIKE_DEFAULT = 'SET_LIKE_DEFAULT';

export const GET_CATEGORIES = 'GET_CATEGORIES';

export const LOGIN_USER = 'LOGIN_USER';
export const CREATE_POST = 'CREATE_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
